### ISSUE TITLE
dataset missing

### ISSUE THREAD

**Issue by pheman** [proceduralia/pytorch-GAN-timeseries#1]
quite an interesting and great project! However I cannot find the btp_dataset.csv to run the project actually as a demo. So could you please attach a dataset?
Thanks!

**Comment by proceduralia** [comment]
Hello pheman,

thank you for the interest in my project! Unfortunately, I was running the method on a confidential dataset, that I am not allowed to publish online. 

I hope this code can still help you,

Pierluca

**Comment by pheman** [comment]
@proceduralia Thanks very much! Yes, this code is of great help for me. I understand that the data is confidential, so could you show the scheme of the btp_dataset with a fake demo?
